<?php
require __DIR__.'/app-bootstrap.php';require_admin();require $privateRootPath.'/src/admin_users_layout.php';
$search=trim((string)($_GET['search']??''));$role=(string)($_GET['role']??'');$where=[];$params=[];
if($search!==''){$where[]='(u.display_name LIKE ? OR u.email LIKE ? OR EXISTS (SELECT 1 FROM artists sa WHERE sa.owner_user_id=u.id AND sa.name LIKE ?))';$term='%'.$search.'%';array_push($params,$term,$term,$term);}
if($role==='admin')$where[]='u.is_admin=1';elseif($role==='artist')$where[]='u.is_admin=0 AND u.is_artist=1';elseif($role==='customer')$where[]='u.is_admin=0 AND u.is_artist=0';
$sql="SELECT u.id,u.display_name,u.email,u.email_verified_at,u.last_login_at,u.is_admin,u.is_artist,u.disabled_at,u.banned_at,u.ban_reason,u.created_at,(SELECT GROUP_CONCAT(a.name ORDER BY a.name SEPARATOR ' · ') FROM artists a WHERE a.owner_user_id=u.id) artist_names FROM users u".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY u.created_at DESC,u.id DESC";$st=$pdo->prepare($sql);$st->execute($params);$users=$st->fetchAll();
admin_users_layout_start('list');admin_users_flash();
?>
<div class="section-title"><div><span class="kicker">CUSTOMERS</span><h1>Users</h1></div><a class="button" href="<?=e(url('admin/users/create'))?>">＋ Create user</a></div>
<section class="panel admin-list-panel"><div class="admin-section-head"><h2>All users</h2><span><?=count($users)?> matching</span></div><form class="user-filter-form" method="get" action="<?=e(url('admin/users'))?>"><label>Search users<input type="search" name="search" value="<?=e($search)?>" placeholder="Name, email or artist alias"></label><label>Role<select name="role"><option value="">All roles</option><option value="admin" <?=$role==='admin'?'selected':''?>>Administrators</option><option value="artist" <?=$role==='artist'?'selected':''?>>Artists</option><option value="customer" <?=$role==='customer'?'selected':''?>>Customers</option></select></label><button class="button" type="submit">Filter</button><?php if($search!==''||$role!==''):?><a class="button secondary" href="<?=e(url('admin/users'))?>">Clear</a><?php endif;?></form><div class="admin-table user-admin-table"><div class="admin-row user-admin-head"><strong>Name</strong><strong>Email</strong><strong>Artist profiles</strong><strong>Role</strong><strong>Validated</strong><strong>Last login</strong><strong>Status</strong><strong>Action</strong></div><?php foreach($users as $x):$banned=!empty($x['banned_at']);$disabled=!empty($x['disabled_at']);?><div class="admin-row"><span><strong><?=e($x['display_name'])?></strong><small>Joined <?=e($x['created_at'])?></small></span><span><?=e($x['email'])?></span><span><?= $x['artist_names']?e($x['artist_names']):'<span class="muted">—</span>' ?></span><span><?php if($x['is_admin']):?><span class="badge">Admin</span><?php elseif($x['is_artist']):?><span class="badge">Artist</span><?php else:?><span class="muted">Customer</span><?php endif;?></span><span><?=$x['email_verified_at']?'<span class="badge">Yes</span>':'<span class="muted">No</span>'?></span><span><?=e($x['last_login_at']?:'Never')?></span><span><?php if($banned):?><span class="badge danger-badge">Banned</span><?php elseif($disabled):?><span class="badge muted">Disabled</span><?php else:?><span class="badge">Active</span><?php endif;?></span><span><a class="button secondary tiny" href="<?=e(url('admin/users/edit/'.(int)$x['id']))?>">Edit</a></span></div><?php endforeach;?><?php if(!$users):?><p class="muted">No users match these filters.</p><?php endif;?></div></section>
<?php admin_users_layout_end(); ?>