<?php
require __DIR__.'/app-bootstrap.php';
$admin=require_admin();
$flash=null;
function discount_date_value(string $value,bool $end=false):?string {
    $value=trim($value);
    if($value==='')return null;
    $d=DateTime::createFromFormat('Y-m-d',$value);
    if(!$d||$d->format('Y-m-d')!==$value)throw new RuntimeException('Enter valid dates.');
    return $value.($end?' 23:59:59':' 00:00:00');
}
function discount_form_values():array {
    $type=$_POST['discount_type']??'percent';if(!in_array($type,['percent','fixed'],true))throw new RuntimeException('Invalid discount type.');
    $kind=$_POST['promotion_kind']??'code';if(!in_array($kind,['code','launch','genre','bundle'],true))throw new RuntimeException('Invalid promotion type.');
    $code=discount_code_normalize((string)($_POST['code']??''));if(!preg_match('/^[A-Z0-9_-]{3,64}$/',$code))throw new RuntimeException('Code must be 3-64 characters using A-Z, 0-9, hyphens or underscores.');
    $value=(int)($_POST['discount_value']??0);if(($type==='percent'&&($value<1||$value>100))||($type==='fixed'&&$value<1))throw new RuntimeException('Enter a valid discount value.');
    $minimum=(float)str_replace(',','',(string)($_POST['minimum_subtotal']??'0'));if(!is_finite($minimum)||$minimum<0)throw new RuntimeException('Enter a valid minimum basket value.');
    $limit=trim((string)($_POST['usage_limit']??''));if($limit!==''&&((int)$limit<1||!ctype_digit($limit)))throw new RuntimeException('Usage limit must be a positive whole number.');
    $userId=(int)($_POST['user_id']??0);if($userId<1)$userId=null;$genreId=(int)($_POST['genre_id']??0);if($kind==='genre'&&$genreId<1)throw new RuntimeException('Choose a genre for a genre sale.');if($kind!=='genre')$genreId=null;
    $minimumItems=max(0,(int)($_POST['minimum_items']??0));if($kind==='bundle'&&$minimumItems<2)throw new RuntimeException('Bundle offers need at least two tracks.');
    return ['code'=>$code,'promotion_kind'=>$kind,'user_id'=>$userId,'genre_id'=>$genreId,'one_time_per_user'=>isset($_POST['one_time_per_user'])?1:0,'discount_type'=>$type,'discount_value'=>$value,'minimum_subtotal_pence'=>(int)round($minimum*100),'minimum_items'=>$minimumItems,'auto_apply'=>$kind==='code'?0:1,'starts_at'=>discount_date_value((string)($_POST['starts_at']??'')),'ends_at'=>discount_date_value((string)($_POST['ends_at']??''),true),'usage_limit'=>$limit===''?null:(int)$limit,'active'=>isset($_POST['active'])?1:0];
}if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        require_csrf();$action=(string)($_POST['action']??'');
        if($action==='discount_delete'){$id=(int)($_POST['id']??0);$pdo->prepare('DELETE FROM discount_codes WHERE id=?')->execute([$id]);$flash=['ok'=>true,'message'=>'Discount deleted.'];}
        elseif($action==='discount_toggle'){$id=(int)($_POST['id']??0);$pdo->prepare('UPDATE discount_codes SET active=1-active WHERE id=?')->execute([$id]);$flash=['ok'=>true,'message'=>'Discount status updated.'];}
        elseif($action==='discount_save'){
            $data=discount_form_values();$id=(int)($_POST['id']??0);
            if($id){$st=$pdo->prepare('SELECT id FROM discount_codes WHERE code=? AND id<>?');$st->execute([$data['code'],$id]);if($st->fetch())throw new RuntimeException('That code already exists.');$sql='UPDATE discount_codes SET code=?,promotion_kind=?,user_id=?,genre_id=?,one_time_per_user=?,discount_type=?,discount_value=?,minimum_subtotal_pence=?,minimum_items=?,auto_apply=?,starts_at=?,ends_at=?,usage_limit=?,active=? WHERE id=?';$pdo->prepare($sql)->execute([$data['code'],$data['promotion_kind'],$data['user_id'],$data['genre_id'],$data['one_time_per_user'],$data['discount_type'],$data['discount_value'],$data['minimum_subtotal_pence'],$data['minimum_items'],$data['auto_apply'],$data['starts_at'],$data['ends_at'],$data['usage_limit'],$data['active'],$id]);}
            else{$st=$pdo->prepare('SELECT id FROM discount_codes WHERE code=?');$st->execute([$data['code']]);if($st->fetch())throw new RuntimeException('That code already exists.');$sql='INSERT INTO discount_codes(code,promotion_kind,user_id,genre_id,one_time_per_user,discount_type,discount_value,minimum_subtotal_pence,minimum_items,auto_apply,starts_at,ends_at,usage_limit,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)';$pdo->prepare($sql)->execute([$data['code'],$data['promotion_kind'],$data['user_id'],$data['genre_id'],$data['one_time_per_user'],$data['discount_type'],$data['discount_value'],$data['minimum_subtotal_pence'],$data['minimum_items'],$data['auto_apply'],$data['starts_at'],$data['ends_at'],$data['usage_limit'],$data['active']]);}
            $flash=['ok'=>true,'message'=>$id?'Discount updated.':'Discount created.'];
        }
    }catch(Throwable $e){$flash=['ok'=>false,'message'=>$e->getMessage()];}
}
$users=$pdo->query('SELECT id,display_name,email FROM users ORDER BY display_name,email')->fetchAll();$genres=$pdo->query('SELECT id,name FROM genres ORDER BY name')->fetchAll();
$codes=$pdo->query('SELECT d.*,u.display_name,u.email FROM discount_codes d LEFT JOIN users u ON u.id=d.user_id ORDER BY d.active DESC,d.created_at DESC,d.id DESC')->fetchAll();
layout_header('Discounts');
?>
<div class="section-title"><div><span class="kicker">SALES TOOLS</span><h1>Discounts</h1></div><span><?=count($codes)?> code<?=count($codes)===1?'':'s'?></span></div>
<?php if($flash):?><div class="panel admin-flash <?=$flash['ok']?'':'error'?>"><?=e($flash['message'])?></div><?php endif;?>
<section class="panel admin-list-panel"><div class="admin-section-head"><h2>Create discount</h2><span>User-locked codes can be used only by the selected customer.</span></div>
<form method="post" class="admin-compact-form cols">
<input type="hidden" name="action" value="discount_save"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<label>Promotion<select name="promotion_kind"><option value="code">Discount code</option><option value="launch">Automatic launch offer</option><option value="genre">Automatic genre sale</option><option value="bundle">Automatic multi-track offer</option></select></label><label>Code<input name="code" maxlength="64" pattern="[A-Za-z0-9_-]{3,64}" placeholder="WELCOME10" required></label>
<label>Type<select name="discount_type"><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label>
<label>Value<input name="discount_value" type="number" min="1" value="10" required><small>Percent 1-100, or pence for fixed amount.</small></label>
<label>Genre (for genre sale)<select name="genre_id"><option value="0">Choose a genre</option><?php foreach($genres as $genre):?><option value="<?=$genre['id']?>"><?=e($genre['name'])?></option><?php endforeach;?></select></label><label>Minimum tracks<input name="minimum_items" type="number" min="0" value="0"><small>Bundle offers require at least two.</small></label><label>Minimum basket (£)<input name="minimum_subtotal" type="number" min="0" step="0.01" value="0"></label>
<label>Starts<input name="starts_at" type="date"></label><label>Ends<input name="ends_at" type="date"></label>
<label>Usage limit<input name="usage_limit" type="number" min="1" placeholder="Unlimited"></label>
<label>Lock to customer<select name="user_id"><option value="0">All customers</option><?php foreach($users as $user):?><option value="<?=$user['id']?>"><?=e($user['display_name'].' · '.$user['email'])?></option><?php endforeach;?></select></label>
<label class="check"><input type="checkbox" name="one_time_per_user"> One use per customer account</label><label class="check"><input type="checkbox" name="active" checked> Active</label>
<button class="button wide">Create discount</button></form></section>
<section class="panel admin-list-panel"><div class="admin-section-head"><h2>Existing codes</h2><span>Disable a code without deleting its history.</span></div><div class="admin-table discount-admin-table">
<?php foreach($codes as $code):?><details class="manage-item"><summary><span><strong><?=e($code['code'])?></strong><small><?=e($code['promotion_kind'])?> · <?=e($code['discount_type']==='percent'?$code['discount_value'].'% off':money((int)$code['discount_value']).' off')?> · <?=e($code['user_id']?$code['display_name'].' · '.$code['email']:'All customers')?></small></span><span><?=e($code['active']?'Active':'Disabled')?> · <?=e((string)$code['used_count'])?> used</span><span class="manage-actions">Edit</span></summary>
<form method="post" class="admin-edit-form cols"><input type="hidden" name="action" value="discount_save"><input type="hidden" name="id" value="<?=$code['id']?>"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<label>Promotion<select name="promotion_kind"><option value="code" <?=$code['promotion_kind']==='code'?'selected':''?>>Discount code</option><option value="launch" <?=$code['promotion_kind']==='launch'?'selected':''?>>Automatic launch offer</option><option value="genre" <?=$code['promotion_kind']==='genre'?'selected':''?>>Automatic genre sale</option><option value="bundle" <?=$code['promotion_kind']==='bundle'?'selected':''?>>Automatic multi-track offer</option></select></label><label>Code<input name="code" value="<?=e($code['code'])?>" required></label><label>Type<select name="discount_type"><option value="percent" <?=$code['discount_type']==='percent'?'selected':''?>>Percentage</option><option value="fixed" <?=$code['discount_type']==='fixed'?'selected':''?>>Fixed amount</option></select></label><label>Value<input name="discount_value" type="number" min="1" value="<?=e($code['discount_value'])?>" required></label><label>Genre (for genre sale)<select name="genre_id"><option value="0">Choose a genre</option><?php foreach($genres as $genre):?><option value="<?=$genre['id']?>" <?=$code['genre_id']==$genre['id']?'selected':''?>><?=e($genre['name'])?></option><?php endforeach;?></select></label><label>Minimum tracks<input name="minimum_items" type="number" min="0" value="<?=e((string)$code['minimum_items'])?>"><small>Bundle offers require at least two.</small></label><label>Minimum basket (£)<input name="minimum_subtotal" type="number" min="0" step="0.01" value="<?=e(number_format($code['minimum_subtotal_pence']/100,2,'.',''))?>"></label><label>Starts<input name="starts_at" type="date" value="<?=e($code['starts_at']?substr($code['starts_at'],0,10):'')?>"></label><label>Ends<input name="ends_at" type="date" value="<?=e($code['ends_at']?substr($code['ends_at'],0,10):'')?>"></label><label>Usage limit<input name="usage_limit" type="number" min="1" value="<?=e((string)($code['usage_limit']??''))?>"></label><label>Lock to customer<select name="user_id"><option value="0">All customers</option><?php foreach($users as $user):?><option value="<?=$user['id']?>" <?=$code['user_id']==$user['id']?'selected':''?>><?=e($user['display_name'].' · '.$user['email'])?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" name="one_time_per_user" <?=$code['one_time_per_user']?'checked':''?>> One use per customer account</label><label class="check"><input type="checkbox" name="active" <?=$code['active']?'checked':''?>> Active</label><div class="form-actions wide"><button class="button">Save</button></div></form>
<form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$code['id']?>"><button class="button secondary" name="action" value="discount_toggle"><?= $code['active']?'Disable':'Enable' ?></button><button class="button danger" name="action" value="discount_delete" onclick="return confirm('Delete this discount code?')">Delete</button></form></details><?php endforeach;?><?php if(!$codes):?><p class="muted">No discount codes have been created yet.</p><?php endif;?></div></section>
<?php layout_footer();