<?php
require __DIR__.'/app-bootstrap.php';
$u=require_login();
if(empty($u['is_admin'])){http_response_code(403);exit('Admin only');}
$st=$pdo->prepare('SELECT admin_2fa_secret,admin_2fa_enabled FROM users WHERE id=?');$st->execute([(int)$u['id']]);$twofa=$st->fetch();$message='';$error='';
$secret=(string)($twofa['admin_2fa_secret']??'');$enabled=(int)($twofa['admin_2fa_enabled']??0)===1;
if(!preg_match('/^[A-Z2-7]{16,64}$/',$secret)){$secret=substr(totp_base32_encode(random_bytes(20)),0,32);$pdo->prepare('UPDATE users SET admin_2fa_secret=?,admin_2fa_enabled=0 WHERE id=?')->execute([$secret,(int)$u['id']]);$enabled=false;}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();try{$code=(string)($_POST['code']??'');if(!totp_verify($secret,$code))throw new RuntimeException('That authenticator code is not valid.');if(isset($_POST['disable'])){$pdo->prepare('UPDATE users SET admin_2fa_enabled=0 WHERE id=?')->execute([(int)$u['id']]);unset($_SESSION['admin_2fa_verified']);$enabled=false;$message='Administrator 2FA disabled.';}elseif($enabled){$_SESSION['admin_2fa_verified']=1;$return=(string)($_SESSION['admin_2fa_return']??'');unset($_SESSION['admin_2fa_return']);redirect($return!==''?$return:'admin.php?section=admins');}else{$pdo->prepare('UPDATE users SET admin_2fa_enabled=1 WHERE id=?')->execute([(int)$u['id']]);$_SESSION['admin_2fa_verified']=1;$enabled=true;$message='Administrator 2FA enabled.';}}catch(Throwable $e){$error=$e->getMessage();}}
$name=site_name();$otpauth='otpauth://totp/'.rawurlencode($name.':'.$u['email']).'?secret='.rawurlencode($secret).'&issuer='.rawurlencode($name);
layout_header('Administrator 2FA');?><section class="auth panel otp-setup"><span class="kicker">ADMIN SECURITY</span><h1>Two-factor authentication</h1><?php if($enabled):?><p class="muted">Two-factor authentication is enabled. Enter the current six-digit code from your authenticator app to continue.</p><?php else:?><div class="otp-setup-grid"><div><p class="muted">Scan this QR code with Google Authenticator, Microsoft Authenticator, 1Password or another compatible app. Then enter the six-digit code shown by the app.</p><div class="otp-qr" id="otp-qr" data-otpauth="<?=e($otpauth)?>"><span>Generating QR code…</span></div></div><div><p class="muted">If scanning is unavailable, enter this setup key manually:</p><p class="otp-secret"><code><?=e($secret)?></code></p><p class="muted small">Keep this key private. It can generate administrator login codes.</p></div></div><?php endif;?><?php if($message):?><p class="success"><?=e($message)?></p><?php endif;?><?php if($error):?><p class="error"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><label><?= $enabled ? 'Current authenticator code' : 'Authenticator code' ?><input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="button"><?= $enabled ? 'Verify and continue' : 'Enable / verify 2FA' ?></button></form></section><?php if(!$enabled):?><script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script>const qr=document.getElementById('otp-qr');if(qr&&window.QRCode){qr.replaceChildren();new QRCode(qr,{text:qr.dataset.otpauth,width:220,height:220,colorDark:'#111827',colorLight:'#ffffff'});}else if(qr){qr.innerHTML='<span>QR unavailable — use the setup key below.</span>';}</script><?php endif;?><?php layout_footer();
