<?php
require __DIR__.'/app-bootstrap.php';
$featured=$pdo->query("SELECT t.*,a.name artist_name,g.name genre_name,r.title release_title,r.artwork_path release_artwork_path,t.artwork_path track_artwork_path,COALESCE(t.release_date,r.release_date,DATE(t.created_at)) effective_date FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN releases r ON r.id=t.release_id LEFT JOIN genres g ON g.id=t.genre_id WHERE t.active=1 AND t.is_featured=1 AND COALESCE(t.release_date,r.release_date,DATE(t.created_at))<=CURDATE() ORDER BY t.id DESC LIMIT 1")->fetchAll();
$newTracks=$pdo->query("SELECT t.*,a.name artist_name,g.name genre_name,r.title release_title,r.artwork_path release_artwork_path,t.artwork_path track_artwork_path,COALESCE(t.release_date,r.release_date,DATE(t.created_at)) effective_date FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN releases r ON r.id=t.release_id LEFT JOIN genres g ON g.id=t.genre_id WHERE t.active=1 AND COALESCE(t.release_date,r.release_date,DATE(t.created_at))<=CURDATE() ORDER BY effective_date DESC,t.id DESC LIMIT 6")->fetchAll();
$hero=$featured[0]??null;
$top=$pdo->query("SELECT t.id,t.title,t.mix_name,t.price_pence,t.bpm,t.preview_path,t.artwork_path track_artwork_path,r.artwork_path release_artwork_path,a.name artist_name,g.name genre_name,COUNT(CASE WHEN o.status='paid' THEN oi.id END) sales FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN releases r ON r.id=t.release_id LEFT JOIN genres g ON g.id=t.genre_id LEFT JOIN order_items oi ON oi.track_id=t.id LEFT JOIN orders o ON o.id=oi.order_id WHERE t.active=1 GROUP BY t.id ORDER BY sales DESC,t.created_at DESC LIMIT 10")->fetchAll();
layout_header();
$heroArt=$hero?track_artwork_url($hero):asset_url('assets/images/hero-bg.svg'); ?>
<section class="hero" style="--hero-art:url('<?=e($heroArt)?>')"><div class="hero-copy"><span class="eyebrow"><?=$hero?'FEATURED TRACK':e(site_name())?></span><?php if($hero):?><h1><em><?=e($hero['title'])?></em><span class="hero-artist"><?=e($hero['artist_name'])?></span></h1><p><?=e($hero['mix_name']?:'Original Mix')?><?=!empty($hero['genre_name'])?' · '.e($hero['genre_name']):''?><?=!empty($hero['bpm'])?' · '.e($hero['bpm']).' BPM':''?></p><div class="hero-actions"><a class="button" href="<?=e(track_public_url($hero))?>">View track</a><button type="button" class="button ghost hero-preview-button" data-preview="<?=e(track_preview_url($hero))?>" data-title="<?=e($hero['title'])?>" data-artist="<?=e($hero['artist_name'])?>" data-art="<?=e($heroArt)?>"><span class="hero-preview-icon" data-play-icon aria-hidden="true">▶</span><span>Play preview</span></button></div><?php else:?><h1>DISCOVER <em>YOUR NEXT SOUND</em></h1><p>Choose a track as Featured in Admin to showcase it here.</p><a class="button" href="admin.php?section=tracks">Choose featured track</a><?php endif;?></div><div class="hero-visual"><img src="<?=e($hero?$heroArt:asset_url('assets/images/brand-orb.svg'))?>" alt=""></div></section>
<section><div class="section-title"><div><span class="kicker">FRESH MUSIC</span><h2>New tracks</h2></div><a href="new-tracks">View all →</a></div><?php if($newTracks):?><div class="cards"><?php foreach(array_slice($newTracks,0,5) as $t) echo track_card($t);?></div><?php else:?><div class="empty-state panel"><img src="<?=e(asset_url('assets/images/empty-art.svg'))?>" alt=""><div><h3>Your catalogue is ready</h3><p>Add an artist, then upload a standalone track in Admin. Releases are optional.</p></div></div><?php endif;?></section>
<section class="home-grid"><div class="panel"><div class="section-title compact"><div><span class="kicker">TRENDING</span><h2>Overall chart</h2></div><a href="charts">Full chart →</a></div><div class="track-table"><?php if(!$top):?><p class="muted">Sales charts will appear after paid orders are recorded.</p><?php endif;?><?php foreach($top as $i=>$t):$t['artist_name']=track_artist_credit($t);$art=track_artwork_url($t);?><div class="track-row"><span class="rank"><?=($i+1)?></span><button class="play round" data-preview="<?=e(track_preview_url($t))?>" data-title="<?=e($t['title'])?>" data-artist="<?=e($t['artist_name'])?>" data-art="<?=e($art)?>">▶</button><img class="track-thumb" src="<?=e($art)?>" alt=""><div class="track-name"><strong><?=e($t['title'])?></strong><small><?=e($t['artist_name'])?><?=$t['mix_name']?' · '.e($t['mix_name']):''?></small></div><span><?=e($t['genre_name']??'')?></span><span><?=$t['bpm']?e((string)$t['bpm']).' BPM':''?></span><strong><?=money((int)$t['price_pence'])?></strong><form method="post" action="<?=e(track_public_url($t))?>" class="quick-add-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="ajax" value="1"><button type="submit" class="button tiny quick-add-button" aria-label="Add <?=e($t['title'])?> to cart" title="Add to cart">🛒</button></form></div><?php endforeach;?></div></div><aside class="feature-stack"><a class="panel trust-card" href="genres"><img src="<?=e(asset_url('assets/images/wave.svg'))?>" alt=""><div><strong>Genre charts</strong><span>Browse the best-selling tracks in each genre.</span></div></a><div class="panel trust-card"><img src="<?=e(asset_url('assets/images/shield.svg'))?>" alt=""><div><strong>Secure downloads</strong><span>Private masters with purchase entitlement checks.</span></div></div><div class="panel trust-card"><img src="<?=e(asset_url('assets/images/profile.svg'))?>" alt=""><div><strong>Artist search</strong><span>Find music by artist name or track title.</span></div></div></aside></section>
<?php layout_footer();
