<?php
require __DIR__.'/app-bootstrap.php';
$u=require_login();
$flash=$_SESSION['support_flash']??null;unset($_SESSION['support_flash']);
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();
    try{
        $subject=trim((string)($_POST['subject']??''));$message=trim((string)($_POST['message']??''));$orderId=(int)($_POST['order_id']??0);
        if($subject===''||mb_strlen($subject)>190)throw new RuntimeException('Enter a subject up to 190 characters.');
        if($message===''||mb_strlen($message)>10000)throw new RuntimeException('Enter a message up to 10,000 characters.');
        if($orderId){$st=$pdo->prepare('SELECT id FROM orders WHERE id=? AND user_id=?');$st->execute([$orderId,(int)$u['id']]);if(!$st->fetch())throw new RuntimeException('That order is not linked to your account.');}
        $pdo->beginTransaction();$pdo->prepare('INSERT INTO support_tickets(user_id,order_id,subject) VALUES(?,?,?)')->execute([(int)$u['id'],$orderId?:null,$subject]);$ticketId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO support_messages(ticket_id,user_id,message) VALUES(?,?,?)')->execute([$ticketId,(int)$u['id'],$message]);$pdo->commit();
        $_SESSION['support_flash']=['message'=>'Your support request has been sent. Reference #'.$ticketId.'.','error'=>false];
        try{send_store_mail((string)mail_settings()['from_email'],'New support request #'.$ticketId,$subject."\n\nFrom: ".(string)$u['email']."\n\n".$message);}catch(Throwable $ignored){error_log('Support notification failed: '.$ignored->getMessage());}
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$_SESSION['support_flash']=['message'=>$e->getMessage(),'error'=>true];}
    redirect('support');
}
$st=$pdo->prepare('SELECT t.*,COUNT(m.id) message_count FROM support_tickets t LEFT JOIN support_messages m ON m.ticket_id=t.id WHERE t.user_id=? GROUP BY t.id ORDER BY t.updated_at DESC');$st->execute([(int)$u['id']]);$tickets=$st->fetchAll();
$orders=$pdo->prepare("SELECT id,created_at,total_pence FROM orders WHERE user_id=? AND status IN ('paid','pending','refunded','cancelled') ORDER BY id DESC LIMIT 50");$orders->execute([(int)$u['id']]);$orderRows=$orders->fetchAll();
layout_header('Customer support');
?><div class="section-title"><div><span class="kicker">HELP DESK</span><h1>Customer support</h1></div><span>We’ll reply by email.</span></div>
<?php if($flash):?><div class="panel account-flash <?=$flash['error']?'is-error':'is-success'?>"><?=e($flash['message'])?></div><?php endif;?>
<div class="support-grid"><section class="panel"><div class="section-title compact"><div><span class="kicker">CONTACT US</span><h2>Open a support request</h2></div></div><form method="post" class="admin-edit-form"><label>Subject<input name="subject" maxlength="190" required></label><label>Related order (optional)<select name="order_id"><option value="0">No specific order</option><?php foreach($orderRows as $order):?><option value="<?=$order['id']?>">Order #<?=$order['id']?> · <?=e(date('j M Y',strtotime($order['created_at'])))?> · <?=money((int)$order['total_pence'])?></option><?php endforeach;?></select></label><label>Message<textarea name="message" rows="9" maxlength="10000" required placeholder="Tell us how we can help..."></textarea></label><input type="hidden" name="action" value="support_create"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><button class="button">Send request</button></form></section><section class="panel"><div class="section-title compact"><div><span class="kicker">YOUR REQUESTS</span><h2>Support history</h2></div></div><?php if(!$tickets):?><p class="muted">You have not opened a support request yet.</p><?php else:?><div class="admin-table support-ticket-list"><?php foreach($tickets as $ticket):?><a class="admin-row" href="support.php?ticket=<?=$ticket['id']?>"><span><strong>#<?=$ticket['id']?> · <?=e($ticket['subject'])?></strong><small><?=e($ticket['updated_at'])?></small></span><span class="status-badge <?=e((string)$ticket['status'])?>"><?=e(str_replace('_',' ',ucfirst((string)$ticket['status'])))?></span></a><?php endforeach;?></div><?php endif;?></section></div>
<?php if(($ticketId=(int)($_GET['ticket']??0))>0):$st=$pdo->prepare('SELECT t.*,u.email FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE t.id=? AND t.user_id=?');$st->execute([$ticketId,(int)$u['id']]);$ticket=$st->fetch();if($ticket):$st=$pdo->prepare('SELECT m.*,COALESCE(u.display_name,au.display_name,"Support") sender FROM support_messages m LEFT JOIN users u ON u.id=m.user_id LEFT JOIN users au ON au.id=m.admin_user_id WHERE m.ticket_id=? ORDER BY m.created_at');$st->execute([$ticketId]);$messages=$st->fetchAll();?><section class="panel support-thread"><div class="admin-section-head"><h2>#<?=$ticket['id']?> · <?=e($ticket['subject'])?></h2><span><?=e(str_replace('_',' ',ucfirst((string)$ticket['status'])))?></span></div><?php foreach($messages as $message):?><article class="support-message"><strong><?=e($message['sender'])?></strong><small><?=e($message['created_at'])?></small><p><?=nl2br(e($message['message']))?></p></article><?php endforeach;?></section><?php endif;endif;?><?php layout_footer();
