<?php
require __DIR__.'/app-bootstrap.php';
$slug=trim((string)($_GET['slug']??''));$id=(int)($_GET['id']??0);if($slug!==''&&preg_match('/-t(\d+)$/',$slug,$slugMatch))$id=(int)$slugMatch[1];
$st=$pdo->prepare("SELECT t.*,a.name artist_name,a.id artist_page_id,a.slug artist_slug,g.name genre_name,g.slug genre_slug,r.title release_title,r.id release_id,r.artwork_path release_artwork_path,r.description release_description,r.catalogue_number,l.name label_name,COALESCE(t.release_date,r.release_date,DATE(t.created_at)) effective_date FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN releases r ON r.id=t.release_id LEFT JOIN labels l ON l.id=r.label_id LEFT JOIN genres g ON g.id=t.genre_id WHERE t.id=? AND t.active=1");$st->execute([$id]);$t=$st->fetch();if(!$t){http_response_code(404);exit('Track not found');}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf();$_SESSION['cart'][$id]=1;if(($_POST['ajax']??'')==='1'){header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'cart_count'=>cart_count(),'track_id'=>$id]);exit;}redirect('cart.php');}
$t['track_artwork_path']=$t['artwork_path']??null;$art=track_artwork_url($t);$mix=trim((string)($t['mix_name']??''))?:'Original Mix';$releaseDate=!empty($t['effective_date'])?date('j M Y',strtotime($t['effective_date'])):null;$fileSize=!empty($t['file_size'])?number_format(((int)$t['file_size'])/1048576,1).' MB':null;
$similar=[];
$similarMix=trim((string)($t['mix_name']??''))?:'Original Mix';
$similarMixExpr="COALESCE(NULLIF(TRIM(t.mix_name),''),'Original Mix')";
try{
    $similarSql="SELECT t.*,a.name artist_name,g.name genre_name,g.slug genre_slug,r.title release_title,r.artwork_path release_artwork_path,t.artwork_path track_artwork_path,COALESCE(t.release_date,r.release_date,DATE(t.created_at)) effective_date,((t.genre_id IS NOT NULL AND t.genre_id=?)*3+(t.artist_id=?)*2+($similarMixExpr=?)*1) similarity_score FROM tracks t JOIN artists a ON a.id=t.artist_id LEFT JOIN releases r ON r.id=t.release_id LEFT JOIN genres g ON g.id=t.genre_id WHERE t.active=1 AND t.id<>? AND (t.genre_id=? OR t.artist_id=? OR $similarMixExpr=?) ORDER BY similarity_score DESC,effective_date DESC,t.id DESC LIMIT 6";
    $similarSt=$pdo->prepare($similarSql);$similarSt->execute([(int)($t['genre_id']??0),(int)$t['artist_id'],$similarMix,$id,(int)($t['genre_id']??0),(int)$t['artist_id'],$similarMix]);$similar=$similarSt->fetchAll();
$GLOBALS['page_meta']=['description'=>$t['title'].' by '.$t['artist_name'].' — '.$similarMix.' on '.site_name(),'image'=>$art,'image_alt'=>$t['title'].' by '.$t['artist_name'],'image_type'=>strtolower((string)($t['mime_type']??'image/jpeg')),'type'=>'music.song','structured'=>['@context'=>'https://schema.org','@type'=>'MusicRecording','name'=>$t['title'],'byArtist'=>['@type'=>'MusicGroup','name'=>$t['artist_name']],'url'=>track_public_url($t),'image'=>$art,'duration'=>'PT90S','offers'=>['@type'=>'Offer','price'=>number_format(((int)$t['price_pence'])/100,2,'.',''),'priceCurrency'=>'GBP','availability'=>'https://schema.org/InStock']]];
}catch(Throwable $ignored){$similar=[];}
$canonicalTrackSlug=track_public_slug($t);if(($slug!==''&&$slug!==$canonicalTrackSlug)||($slug===''&&!empty($_GET['id']))){header('Location: '.track_public_url($t),true,301);exit;}
layout_header($t['title']);?>
<section class="track-detail-shell"><nav class="track-breadcrumb"><a href="<?=e(url('tracks'))?>">Tracks</a><span>›</span><a href="<?=e(url('artists/'.rawurlencode(artist_public_slug(['slug'=>$t['artist_slug']]))))?>"><?=e($t['artist_name'])?></a><span>›</span><span><?=e($t['title'])?></span></nav>
<div class="track-hero-card panel"><div class="track-art-stage"><img class="track-art-large" src="<?=e($art)?>" alt="<?=e($t['title'])?> artwork"><button class="track-art-play" data-preview="<?=e(track_preview_url($t))?>" data-title="<?=e($t['title'])?>" data-artist="<?=e($t['artist_name'])?>" data-art="<?=e($art)?>" aria-label="Play preview"><span data-play-icon>▶</span></button><span class="track-preview-badge">90 SEC PREVIEW</span></div>
<div class="track-main-info"><div class="track-kickers"><?php if($t['genre_name']):?><a href="<?=e(url('charts/'.rawurlencode((string)$t['genre_slug'])))?>"><?=e($t['genre_name'])?></a><?php endif;?><?php if($t['bpm']):?><span><?=e((string)$t['bpm'])?> BPM</span><?php endif;?><span>Individual digital track</span></div><?php if($t['release_title']):?><p class="track-release-label">Part of <?=e($t['release_title'])?></p><?php endif;?><h1><?=e($t['title'])?></h1><h2><a href="<?=e(url('artists/'.rawurlencode(artist_public_slug(['slug'=>$t['artist_slug']]))))?>"><?=e($t['artist_name'])?></a></h2><p class="track-mix"><?=e($mix)?></p><div class="track-primary-actions"><form method="post" action="<?=e(url('favourites.php'))?>" class="favourite-form track-favourite-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="track_id" value="<?=$t['id']?>"><input type="hidden" name="ajax" value="1"><button type="submit" class="button secondary favourite-toggle <?=is_track_favourite((int)$t['id'])?'is-favourite':''?>" aria-label="<?=is_track_favourite((int)$t['id'])?'Remove':'Save'?> <?=e($t['title'])?> <?=is_track_favourite((int)$t['id'])?'from':'to'?> favourites" title="<?=is_track_favourite((int)$t['id'])?'Remove from':'Save to'?> favourites"><?=is_track_favourite((int)$t['id'])?'♥ Saved':'♡ Save to favourites'?></button></form><button class="button secondary track-preview-button" data-preview="<?=e(track_preview_url($t))?>" data-title="<?=e($t['title'])?>" data-artist="<?=e($t['artist_name'])?>" data-art="<?=e($art)?>"><span data-play-icon>▶</span> Preview track</button><form method="post" class="track-buy-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><button class="button track-buy-button" type="submit"><span>Add to cart</span><strong><?=money((int)$t['price_pence'])?></strong></button></form></div><div class="track-assurance-row"><span>◆ Secure purchase</span><span>↓ Limited protected downloads</span><span>♪ High-quality master</span></div></div></div>
<div class="track-lower-grid"><section class="panel track-about"><div class="section-title compact"><div><span class="eyebrow">TRACK</span><h2>About this track</h2></div></div><?php if(!empty($t['release_description'])):?><p><?=nl2br(e($t['release_description']))?></p><?php else:?><p class="muted">Preview this individual track above. Purchased files are delivered securely from RecordStore's private master storage.</p><?php endif;?></section><aside class="panel track-specs"><div class="section-title compact"><div><span class="eyebrow">DETAILS</span><h2>Track info</h2></div></div><dl><div><dt>Artist</dt><dd><a href="<?=e(url('artists/'.rawurlencode(artist_public_slug(['slug'=>$t['artist_slug']]))))?>"><?=e($t['artist_name'])?></a></dd></div><div><dt>Mix</dt><dd><?=e($mix)?></dd></div><?php if($t['genre_name']):?><div><dt>Genre</dt><dd><a href="<?=e(url('charts/'.rawurlencode((string)$t['genre_slug'])))?>"><?=e($t['genre_name'])?></a></dd></div><?php endif;?><?php if($t['bpm']):?><div><dt>BPM</dt><dd><?=e((string)$t['bpm'])?></dd></div><?php endif;?><?php if($t['release_title']):?><div><dt>Release</dt><dd><?=e($t['release_title'])?></dd></div><?php endif;?><?php if($t['label_name']):?><div><dt>Label</dt><dd><?=e($t['label_name'])?></dd></div><?php endif;?><?php if($t['catalogue_number']):?><div><dt>Catalogue</dt><dd><?=e($t['catalogue_number'])?></dd></div><?php endif;?><?php if($releaseDate):?><div><dt>Released</dt><dd><?=e($releaseDate)?></dd></div><?php endif;?><?php if($fileSize):?><div><dt>Master size</dt><dd><?=e($fileSize)?></dd></div><?php endif;?></dl></aside></div></section><?php if($similar): ?><section class="similar-tracks"><div class="section-title"><div><span class="kicker">YOU MAY ALSO LIKE</span><h2>Similar tracks</h2></div><span><?=count($similar)?> suggestions</span></div><div class="cards similar-track-cards"><?php foreach($similar as $similarTrack) echo track_card($similarTrack); ?></div></section><?php endif; ?>
<?php layout_footer();
